### ISSUE TITLE
[DEPLOYMENT] issues in deployment

### ISSUE THREAD

**Issue by KalaRaja** [airavata-courses/CAPtivate#77]
Hi team,

I have deployed kafka, api-gateway, db-docker, session-management, UserManagement, data-retrieval, postprocessing, model execution microservices with no errors.

But I get the dollowing error in the front end: 
![Screen Shot 2020-02-21 at 9 28 12 PM](https://user-images.githubusercontent.com/42894144/75084840-1ab2d300-54f1-11ea-9427-6b64752706b4.png)
![Screen Shot 2020-02-21 at 9 27 24 PM](https://user-images.githubusercontent.com/42894144/75084842-1edef080-54f1-11ea-833d-df4e71c21b32.png)

Also, in your wiki, you need to mention the name of release branch.

**Comment by rasmitha-koduru** [comment]
Hi Shashank,

I think it is because of the react scripts version you are getting this error. It was working fine when we tested. 
Quick fix is to update the react scripts version in package.json from 3.3.1 to 3.4.0
"react-scripts": "3.3.1" to "react-scripts": "3.4.0".
We will be updating the package.json and readme file soon.
I think this is the latest fix released by react since it was working fine with 3.3.1!
Also we are working on dockerization of UI to avoid these issues. Sorry for the inconvenience.

**Comment by KalaRaja** [comment]
front end works now, thanks.
